name: "Cache Node and NPM Dependencies"
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
  node-version:
    description: "Node.js version to use."
    required: true
    default: "20.x"
  working-dir:
    description: "The working directory of the application."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Setup NodeJS version"
      uses: actions/node@v4
      with:
        version: ${{ inputs.node-version }}
    - name: "Cache dependencies"
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: "Install dependencies"
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}